---
title: "task1"
output: html_document
date: "2023-02-25"
---

```{r}
install.packages("tidyr")
```

```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(reshape2)
```

```{r}
data <- read_excel("addicts1.xlsx", sheet = 2)
data <- data %>% select(prcod, intpla, curwor, educat, sex, end) %>% na.omit()
head(data)
```

```{r}
# Построение по вектору численных значений матрицы инцидетности.
numeric.to.binary <- function(column, name) {
  value <- sort(unique(column))
  names <- c()
  for (i in value) {
    names <- c(names, paste(name, i, sep="_"))
  }
  
  if (0 %in% value)
    column <- column + 1
  
  matrix.data <- matrix(0, ncol = length(value), nrow = length(column))
  for (i in 1:length(column)) {
    matrix.data[i, column[i]] <- 1
  }
  
  df.data <- as.data.frame(matrix.data)
  colnames(df.data) <- names
  df.data
}

# Построение матрицы инцидентности.
df.to.binary <- function(df) {
  names <- colnames(df)
  df.data <- numeric.to.binary(as.numeric(unlist(df[, 1])), names[1])
  for (i in 2:length(names)) {
    df.data <- cbind(df.data, numeric.to.binary(as.numeric(unlist(df[, i])), names[i]))
  }
  df.data
}

data.new <- df.to.binary(data)
head(data.new)
```

```{r}
pc<-princomp(data.new)
```

Сдандартное отклонение главных коммпонент:
```{r}
pc$sdev
```

Факторные нагрузки:
```{r}
pc$loadings[,1:4]
```



Значения главных компонент:
```{r}
pc$scores[1:10, 1:4]
```










